# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmarks < Formula
  desc ""
  homepage "https://github.com/greggannicott/tmarks"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.2/tmarks_Darwin_x86_64.tar.gz"
      sha256 "f50cee09608e19ebe895d4b08e99879632915055d976d17d631455e152f15482"

      def install
        bin.install "tmarks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.2/tmarks_Darwin_arm64.tar.gz"
      sha256 "dae87a2290180106b78445cc0d5d60ba6f3af335c16dd7c6e5e2d9707899b056"

      def install
        bin.install "tmarks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.2/tmarks_Linux_x86_64.tar.gz"
      sha256 "e89c28d8bcbb9f93ecfdc4d3189ef6527609e43f2a1f0dcca104e70e15e4313c"

      def install
        bin.install "tmarks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.2/tmarks_Linux_arm64.tar.gz"
      sha256 "04c35b7345299be7a99272b544104496f53ffcf93ed505fe0c0cf045cef12fee"

      def install
        bin.install "tmarks"
      end
    end
  end
end
