# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmarks < Formula
  desc ""
  homepage "https://github.com/greggannicott/tmarks"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.3/tmarks_Darwin_x86_64.tar.gz"
      sha256 "183a8cd97a1e136f62ca5cdf160555bb0a220d594000be625f6dd3a53cbbef58"

      def install
        bin.install "tmarks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.3/tmarks_Darwin_arm64.tar.gz"
      sha256 "eb14edf74bcb3c6abd4576ccdfac5977aeeea4de30e33051cd510fda272a692d"

      def install
        bin.install "tmarks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.3/tmarks_Linux_x86_64.tar.gz"
      sha256 "69f3ed71fcc9223b572130d6db2f79bfaaaf0dea29d7e2cb9e1b7b6bb7221c0a"

      def install
        bin.install "tmarks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.3/tmarks_Linux_arm64.tar.gz"
      sha256 "c91fceb6b90446f4bddddfe75b31336e87847467c1c1aeb4ad8dfb9fe57e1ba9"

      def install
        bin.install "tmarks"
      end
    end
  end
end
