# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmarks < Formula
  desc ""
  homepage "https://github.com/greggannicott/tmarks"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.4/tmarks_Darwin_x86_64.tar.gz"
      sha256 "2bc2dc683a5db14fc77b901f4a10a341778f63ef2d5291b8dc852d4fcaa437f6"

      def install
        bin.install "tmarks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.4/tmarks_Darwin_arm64.tar.gz"
      sha256 "53392957a4c5cb7b37b076754615dae411e561901c045d19dd54c3505cb63f85"

      def install
        bin.install "tmarks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.4/tmarks_Linux_x86_64.tar.gz"
      sha256 "c181ce80c176d86a669a02afe785cb48d5b48a82d2f32f1790f2a19c9c39e7dd"

      def install
        bin.install "tmarks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greggannicott/tmarks/releases/download/v0.0.4/tmarks_Linux_arm64.tar.gz"
      sha256 "f0ba047e578a2a346ad41b394b282cf5479aca41bc5a2768465644be0afb232c"

      def install
        bin.install "tmarks"
      end
    end
  end
end
