# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxTooYoung < Formula
  desc ""
  homepage "https://github.com/greggannicott/tmux-too-young"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.0/tmux-too-young_Darwin_arm64.tar.gz"
      sha256 "87dea030475f67bb8e3168d664dfceb5cccbaac8bec281f5e427d9ad7aa993ca"

      def install
        bin.install "tmux-too-young"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.0/tmux-too-young_Darwin_x86_64.tar.gz"
      sha256 "3abe4769d9201c98af9cdfd155aa5ae5a5ff4c102894ad3b7ad012989fee6a2f"

      def install
        bin.install "tmux-too-young"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.0/tmux-too-young_Linux_x86_64.tar.gz"
      sha256 "c6b4d83a2d990b516f97ea9883949b4e8dc91094066f8af15a8db71e09e312c6"

      def install
        bin.install "tmux-too-young"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.0/tmux-too-young_Linux_arm64.tar.gz"
      sha256 "677d485a0042b57b98411f136f34edacb307577613e766e999eb83f18ed00be2"

      def install
        bin.install "tmux-too-young"
      end
    end
  end
end
