# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxTooYoung < Formula
  desc ""
  homepage "https://github.com/greggannicott/tmux-too-young"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.4/tmux-too-young_Darwin_x86_64.tar.gz"
      sha256 "05caf7d93ba7e701bc08c809a854d81f9ec70ebc9558afba634a8722e18691ef"

      def install
        bin.install "tmux-too-young"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.4/tmux-too-young_Darwin_arm64.tar.gz"
      sha256 "122b969d7675cc677f0386a70c553e1a7931d0b54bd13d00811235c36da563c0"

      def install
        bin.install "tmux-too-young"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.4/tmux-too-young_Linux_x86_64.tar.gz"
      sha256 "d87717bdd08af7c0910851512f539862fc088e51416db7907129afad6bc20fc5"
      def install
        bin.install "tmux-too-young"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.1.4/tmux-too-young_Linux_arm64.tar.gz"
      sha256 "c750bd8af21f784c866521aaa3be3b92cc73f9dc77ba9499445e167f6565553f"
      def install
        bin.install "tmux-too-young"
      end
    end
  end
end
