# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxTooYoung < Formula
  desc ""
  homepage "https://github.com/greggannicott/tmux-too-young"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.0.9/tmux-too-young_Darwin_arm64.tar.gz"
      sha256 "1673a13bc3e8960e935e3b5b67ff255446fa43d647196eacb8bb4e51ea0a732d"

      def install
        bin.install "tmux-too-young"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.0.9/tmux-too-young_Darwin_x86_64.tar.gz"
      sha256 "ef3e891af1195e60b41c7c163af424fae82a8545ae034cb5d5f6c396ea2ffcb5"

      def install
        bin.install "tmux-too-young"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.0.9/tmux-too-young_Linux_arm64.tar.gz"
      sha256 "b8d7a4434cb1b073a0117c6c3c7c334b6b46dfe023f8f63770a978b38cddbcef"

      def install
        bin.install "tmux-too-young"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/greggannicott/tmux-too-young/releases/download/v0.0.9/tmux-too-young_Linux_x86_64.tar.gz"
      sha256 "f75cebcd5740e7570fbef839b7df72dcf187def5a5c7b1e01b415dc9ccc2ef48"

      def install
        bin.install "tmux-too-young"
      end
    end
  end
end
